export const gameInstructions = {
  '2048': [
    'Slide the tiles with the arrow keys or swipe across the board.',
    'Two tiles with the same value merge when pushed together. Each tile can merge once per move.',
    'Combine tiles to reach 2048. Merges add to your score.',
    'Undo reverses your last move; Undo 5x steps back through up to five moves. Reset restarts the board.',
    'Daily Challenge gives everyone the same starting puzzle. Classic and Unlimited offer other ways to play.',
  ],
  hashi: [
    'Connect the numbered islands with horizontal or vertical bridges. Each island’s number is the total bridges it needs.',
    'Click or tap between two visible islands to place one bridge. Click again for a double bridge, and again to remove it.',
    'Bridges cannot cross or pass through another island. Only the nearest island in each direction can be connected.',
    'Match every island’s number and connect all islands into one network to win.',
  ],
  minesweeper: [
    'Reveal every safe cell without opening a mine.',
    'A number tells you how many mines occupy its eight surrounding cells, including diagonals.',
    'Click or tap to reveal a cell. Right-click, or long-press on touch screens, to place or remove a flag.',
    'Click a revealed number after flagging that many neighbors to reveal the remaining neighbors. Incorrect flags can cause a mine to open.',
    'Flags are reminders; winning requires revealing all safe cells.',
  ],
  nerdle: [
    'Find the hidden 10-character equation in six guesses. Every guess must be a valid equation with equal values on both sides of the equals sign.',
    'Use digits, arithmetic operators, parentheses, and the square/cube keys to build your equation.',
    'Green means the character is in the correct position. Yellow means it appears elsewhere. Other characters are absent or used too many times.',
    'Select a cell to edit it, use Delete to erase, and Enter to submit. Match the exact target equation to win.',
  ],
  nonograms: [
    'Fill cells to reveal the hidden pattern. Numbers beside a row or above a column describe its consecutive runs of filled cells, in order.',
    'Leave at least one empty cell between runs. A clue of 0 means the whole line is empty.',
    'Choose Fill or Cross, then click and drag across cells. Right-click places or removes a cross.',
    'Crosses are optional notes. Fill exactly the correct cells to complete the puzzle.',
  ],
  pipes: [
    'Rotate the pipe tiles to connect the entire network to the server.',
    'Click or tap a tile to rotate it clockwise. Every pipe opening must meet a matching opening on its neighbor; no pipe may point off the board.',
    'Right-click to lock or unlock a tile. Locked tiles are darkened and cannot be rotated until unlocked.',
    'Win by powering every tile with no unmatched connections.',
  ],
  quordle: [
    'Solve four five-letter words using at most nine guesses. Each submitted guess is checked against all four boards.',
    'Green letters are in the correct position; yellow letters belong elsewhere in that word. Absent letters do not belong, or appear too many times.',
    'Type using your keyboard or the on-screen keys. Use Enter to submit and Backspace to edit.',
    'A solved board keeps its solution while you continue working on the others. Solve all four before your guesses run out.',
  ],
  shikaku: [
    'Divide the entire grid into non-overlapping rectangles.',
    'Every rectangle must contain exactly one number. Its area, measured in cells, must equal that number.',
    'Click or touch and drag between opposite corners to draw a rectangle. Drawing over an existing rectangle replaces it.',
    'Click an existing rectangle to remove it. Cover every cell with valid rectangles to win.',
  ],
  'skeedle-marathon': [
    'Solve 26 five-letter words with a shared pool of 31 guesses.',
    'Every guess is evaluated across all boards. Green marks a correct letter and position; yellow marks a letter in the wrong position.',
    'Use the keyboard to type and Enter to submit. Select an unsolved board to focus on its feedback.',
    'Solved boards hide automatically. Solve every board before you run out of guesses.',
  ],
  stitches: [
    'Connect every pair of blocks sharing an edge with exactly one stitch. Blocks touching only at a corner are not neighbors.',
    'Tap a thick boundary between two cells to place a stitch. Its two endpoints are holes, and no hole may belong to more than one stitch. Tap again to remove it.',
    'The outside clues count holes in each row and column. Bright green means the count matches; pink means there are too many.',
    'Use Mark empty to add optional × notes. Right-click and drag to mark several cells; starting on an × erases marks. Undo reverses the whole drag.',
    'You can also Tab to cells or boundaries and use Enter or Space. Match all clues and connect every neighboring block pair to win.',
  ],
  sudoku: [
    'Fill each row, column, and outlined box with every number from 1 to the board size, without repeats.',
    'The starting clues cannot be changed. Select an empty cell, then enter a number using the keyboard or number buttons.',
    'Use Notes mode to record possible values without filling the cell. Remove candidates as you rule them out.',
    'Complete every cell correctly to win. Mini boards use smaller number ranges and boxes; standard boards use 1–9.',
  ],
  word500: [
    'Find the hidden five-letter word in eight guesses.',
    'The feedback gives totals: green counts letters in the correct position, yellow counts correct letters elsewhere, and pink counts absent or excess letters.',
    'The totals do not identify which letters match. Click submitted tiles to cycle your own color notes as you reason it out.',
    'Type a valid five-letter word and press Enter to submit. Match the target exactly to win.',
  ],
  map: [
    'Color every region with one of four colors. Regions sharing an edge must have different colors; regions touching only at a corner may match.',
    'Locked regions are fixed clues. Choose a palette color and select an unlocked region, or drag a colored region onto another to copy its color.',
    'Use pencil mode for candidate colors. Right-click an empty region to toggle a note, or right-drag a colored region into an empty region to copy a note.',
    'Press 1–4 to select a color, E for the eraser, P for pencil mode, and L for region labels. Escape cancels a drag.',
    'Fill every region with no matching neighbors to win. Undo, Redo, Reset, and Hint are available in the side panel.',
  ],
};
